# Generated by Django 5.1.2 on 2024-11-07 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50, unique=True, verbose_name='Name')),
                ('lastname', models.CharField(max_length=50, verbose_name='Surname')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email')),
                ('address', models.CharField(max_length=50)),
                ('phonenum', models.BigIntegerField(default=0, verbose_name='Phone Number')),
            ],
        ),
    ]
