# Generated by Django 5.1.2 on 2024-11-07 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yogaapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='customer',
            table='yoga_mini',
        ),
    ]
