# Generated by Django 5.1.2 on 2024-11-07 20:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yogaapp', '0002_alter_customer_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='date',
            field=models.DateField(default=datetime.date.today, verbose_name='date'),
        ),
        migrations.AddField(
            model_name='customer',
            name='time',
            field=models.TimeField(default=datetime.time(5, 0), verbose_name='time'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phonenum',
            field=models.BigIntegerField(verbose_name='Phone Number'),
        ),
    ]
