# Generated by Django 5.1.2 on 2024-11-09 05:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yogaapp', '0003_customer_date_customer_time_alter_customer_phonenum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='firstname',
            field=models.CharField(max_length=50, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='time',
            field=models.TimeField(default=datetime.time(0, 0), unique=True, verbose_name='time'),
        ),
    ]
