# Generated by Django 5.1.2 on 2024-11-09 05:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yogaapp', '0004_alter_customer_firstname_alter_customer_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='time',
            field=models.TimeField(default=datetime.time(0, 0), verbose_name='time'),
        ),
        migrations.AlterUniqueTogether(
            name='customer',
            unique_together={('date', 'time')},
        ),
    ]
