# Generated by Django 5.1.2 on 2024-11-09 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yogaapp', '0006_alter_customer_unique_together_alter_customer_table'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='customer',
            unique_together={('date', 'time')},
        ),
        migrations.AlterModelTable(
            name='customer',
            table='yoga_mini',
        ),
    ]
