# Generated by Django 5.1.2 on 2024-11-09 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yogaapp', '0007_alter_customer_unique_together_alter_customer_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='firstname',
            field=models.CharField(max_length=50, unique=True, verbose_name='Name'),
        ),
    ]
