# Generated by Django 5.1.2 on 2024-11-09 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yogaapp', '0008_alter_customer_firstname'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='customer',
            unique_together=set(),
        ),
    ]
