# Generated by Django 5.1.2 on 2024-11-09 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yogaapp', '0009_alter_customer_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='customer',
            unique_together={('date', 'time')},
        ),
    ]
